### ISSUE TITLE
Infinite "player is joining" in the custom match lobby.

### ISSUE THREAD

**Issue by sephoroid** [unixoide/5th-echelon#14]
I have tested the fix in SvM mode with two other players and with one it sometines works fine, while with the other one it doesnt work at all.

Issue is that when player gets invited to a custom match, he can see "attempting to join a game session"
while host can see him in the lobby, but instead of his name there is message "player is joining" this state lasts forever for some reason.

I have not seen an issue like that ever before using this fix.

One player who tries to join me has this issue randomly, while the other one has it every single time.

We all have tested this with DMZ host, so all connections were fully open.
Firewalls were disabled.

Did anyone else get this issue?
Any solutions?

**Comment by TheConen** [comment]
A buddy of mine and I had the same problem. We just used the public matchmaking instead which always put us in the same lobby and worked without any problems.

**Comment by sephoroid** [comment]
> A buddy of mine and I had the same problem. We just used the public matchmaking instead which always put us in the same lobby and worked without any problems.

The only problem is that public match wont start if player count is too low.
This is why I would like to play custom matches instead.
This way I could gather some wireshark info when I play.

**Comment by TheConen** [comment]
Well, we were playing Coop, not SvM, so we didn't have that problem^^

**Comment by JordanLeich** [comment]
@sephoroid Make sure all players uninstalled radmin or hamachi. Also, if players are having trouble connecting to others, then they should disable their windows defender and any other antivirus as this is what helped me in some instances.

**Comment by K4CZP3R** [comment]
Maybe we should try to capture packets using wireshark?

**Comment by unixoide** [comment]
A Wireshark recording could be helpful. Without it can't say much.
