### ISSUE TITLE
creating your own dedicated SCBL server

### ISSUE THREAD

**Issue by DRS490** [unixoide/5th-echelon#17]
Tell me how to raise my server using these files? I just can’t figure out where to change the ip, how to connect the friends system, etc. I would be grateful if one of you describes everything point by point, preferably with screenshots of each procedure
In general, make a clear tutorial for creating your own dedicated server, I will be very grateful to you

**Comment by unixoide** [comment]
An upcoming change will make it easier to use. For now:

# one time setup
1. Get the zip file from [here](https://github.com/unixoide/5th-echelon/releases/tag/2023-11-29)
2. Unpack it somewhere (for example on your desktop)
3. Go to your game installation folder and then into `src`, then `SYSTEM`
4. Rename the `uplay_r1_loader.dll` to `uplay_r1_loader.orig.dll`
5. Get the updated binaries from [here](https://github.com/unixoide/5th-echelon/releases/tag/2023-12-12)
    1. Copy the `uplay_r1_loader.dll` from the 2nd zip file to the game folder (`your\game\directory\src\SYSTEM`)
    2. Replace the `dedicated_server.exe` in the previously unpacked folder with the one from the 2nd zip file
 6. In the unpacked folder edit the `services.toml` file by adding `api_server = "127.0.0.1:50051"` after the `services = ...` line:
     ```toml
     services = ["sc_bl_secure", "sc_bl_auth", "onlineconfig", "content"]
     ```
     becomes
     ```toml
     services = ["sc_bl_secure", "sc_bl_auth", "onlineconfig", "content"]
     api_server = "127.0.0.1:50051"
     ```
7. Start the DX9 binary. You should see a message box saying that a config file was created.
8. Go to the game directory (`your\game\directory\src\SYSTEM`) and verify that there is a `uplay.toml` file with this line: `ApiServer = "http://127.0.0.1:50051"`
    1. if there is no such line, add it after `ConfigServer  = ...` like so:
    ```toml
    ConfigServer = "127.0.0.1"
    ApiServer = "http://127.0.0.1:50051/"
    ```

# testing it

1. Run the `dedicated_server.exe` binary
2. Start the DX9 version of the game
3. Try to go online

> [!NOTE]
> The currently released version of the code only supports for a single individual to start a game session and join it (aka "go online"), **no working multiplayer!**. This requires to correctly setting up a peer-to-peer connection and I sadly haven't received any network recordings while the fix worked so finding the correct implementation is harder.

# Undoing the changes

To revert everything back to normal, delete the `uplay_r1_loader.dll` and rename `uplay_r1_loader.orig.dll` back to `uplay_r1_loader.dll`.
