### ISSUE TITLE
Blacklist_DX11_game isn't supported

### ISSUE THREAD

**Issue by Zl0gix** [unixoide/5th-echelon#18]
Hi,
After installing your patches and launching the game, i get the error message : "blacklist_dx11_game.exe was modified or the version is not supported"

I'm adding the game exe to the issue so you can look it up, last time the .exe was modified seems to be 26 october 2021
(file hash is : "C52B3D0927591E477424F389FF0B1314A300938E19CE61A7B0A7BC09F81C2C89", via PS Get-FileHash command)

For the record this is how I installed the patches :
- I changed the uplay_r1_loader.dll
- launched the dedicated server to generate the service.toml file
- relaunched the dedicated server
- launched the game to create the uplay.toml file
- relaunched the game but I get the error 

Thank you for your work and sorry if the error is simply due to me doing something wrong during the installation.

[Blacklist_DX11_game.zip](https://github.com/unixoide/5th-echelon/files/14733122/Blacklist_DX11_game.zip)

**Comment by MPW1412** [comment]
Hi,

we've run into this aswell. You can go back to the original dll, run the game and switch to DX9. Then close it, change the dlls back to the new one and the game starts.

Best,
Matthias

**Comment by unixoide** [comment]
Yes, the DX11 binary is not supported right now, you have to use the DX9 binary. An upcoming change will fix that.

**Comment by unixoide** [comment]
This should be fixed now.
