### ISSUE TITLE
Run dedicated_server on public IP to bypass NAT issues?

### ISSUE THREAD

**Issue by MPW1412** [unixoide/5th-echelon#19]
Hello everyone and thanks for this awesome project! It's amazing to see, I'm not the only person on the planet missing this game so bad.

The Ubisoft servers are down again, so we tried to run the dedicated_server. You can start a private match with just one player. Nice :)

What would be the next steps to actually have a multiplayer SvM game?

In README you wrote, that actual playing is not possible right now due to lack of NAT implementation. I thought about running dedicated_server on an public server so NAT wouldn't be necessary. They are available for little money at various hosters.

However, they usually don't feature Windows but Linux. I tried compiling the source code on Linux. 

Questions:

 - Does dedicated_server need stuff from Blacklist game folder or can it run on its own on another server?
 - Am I on the right path here?
 - Do you have any idea what this failing dependency does?
 
 ```
 dedicated-server:~/5th-echelon# cargo +nightly build --release
   Compiling proc-macro2 v1.0.70
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.150
   Compiling autocfg v1.1.0
   Compiling version_check v0.9.4
   Compiling quote v1.0.33
   Compiling serde v1.0.193
   Compiling syn v2.0.39
   Compiling ahash v0.8.6
   Compiling cfg-if v1.0.0
   Compiling futures-core v0.3.29
   Compiling typenum v1.17.0
   Compiling cc v1.0.83
   Compiling generic-array v0.14.7
   Compiling once_cell v1.18.0
   Compiling getrandom v0.2.11
   Compiling slab v0.4.9
   Compiling futures-task v0.3.29
   Compiling memchr v2.6.4
   Compiling serde_derive v1.0.193
   Compiling futures-util v0.3.29
   Compiling tracing-attributes v0.1.27
   Compiling zerocopy v0.7.26
error[E0635]: unknown feature `stdsimd`
  --> ./src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

Thanks for reading!

Best,
Matthias

**Comment by unixoide** [comment]
> What would be the next steps to actually have a multiplayer SvM game?

Figuring out how to correctly set up the game instances to talk to each other correctly. I have a state where they start communicating, but it goes on forever most of the time (in very rare circumstances it works). This feels like I'm sending some wrong bytes somewhere and sometimes by chance they can be correct and everything works.

> Does dedicated_server need stuff from Blacklist game folder or can it run on its own on another server?

No, it has no further dependencies.

> Am I on the right path here?

The server needs to be reachable by all parties, so yes (but this could also be done through a VPN). But the missing NATTraversal part is related to an implementation detail in which the server helps the game instances to establish a peer-to-peer connection between each other through NAT.

> Do you have any idea what this failing dependency does?

Can you post the rust version you're using? The compile error originates in a dependency (`ahash`), not my code.

**Comment by MPW1412** [comment]
> Unfortunately I never received any recordings from other players while the fix worked, so I don't have enough data to compare.

Oh damn, that sounds like a missed opportunity.

> No, it has no further dependencies.

Okay, cool.

> Can you post the rust version you're using?

```# cargo --version
cargo 1.79.0-nightly (a510712d0 2024-03-25)
```

Which version do you use for compiling?

**Comment by OrangeGrays** [comment]
> Which version do you use for compiling?

I am guessing they used 1.74 nightly, as stated in the build instructions ;-)

**Comment by unixoide** [comment]
I'll upgrade to a newer version in the next release, but yes. The version used is always mentioned in the readme and set automatically by a [rust-toolchain.toml](https://github.com/unixoide/5th-echelon/blob/main/rust-toolchain.toml)
