### ISSUE TITLE
Coop

### ISSUE THREAD

**Issue by souhaibHadded03** [unixoide/5th-echelon#20]
Have you tested the coop mode? I believe it should be a little easier to handle than svm

**Comment by unixoide** [comment]
Yes, I mainly develop against coop right now.

**Comment by souhaibHadded03** [comment]
> Yes, I mainly develop against coop right now.

Good luck man, thank you so much for trying to save this game

I hope the Wireshark records that you received today are enough to finish this project :))

**Comment by unixoide** [comment]
Published the newest version, please give it a try

**Comment by souhaibHadded03** [comment]
> Published the newest version, please give it a try

Thank you so much i will try this and provide Wireshark recprds or anything that can help you to improve this, you literally saved this game ^^
