### ISSUE TITLE
Fixes not Working

### ISSUE THREAD

**Issue by Ieida** [unixoide/5th-echelon#22]
With the dedicated server I get the "Could not latest multiplayer data." message, and with the latest fix for that, it's the same old "Blacklist service not available." I am able to access the friends menu, but not online.

Can someone confirm that any of this still works? My region is Europe Southeast.

**Comment by unixoide** [comment]
I didn't have the time to publish a new version of the server yet. Regardless, the mpdata fix doesn't work anymore as the Ubisoft servers are gone for good.

In the future you or someone else will have to host your own server (what I'm implementing here) and players have to connect to that server.

**Comment by pelmenipadi** [comment]
For me hosting a lobby is working. Can you please implement a guide on how to let people join the lobby so I can play Coop with a friend? I guess VPN is necessary as NAT traversal is not working?

Thank you :) Great work!

**Comment by Koteyka-dev** [comment]
> For me hosting a lobby is working. Can you please implement a guide on how to let people join the lobby so I can play Coop with a friend? I guess VPN is necessary as NAT traversal is not working?
> 
> Thank you :) Great work!

Co-op is not working in current release. You need to wait, when new version of server emulator will be available.

**Comment by unixoide** [comment]
Published the newest version, please give it a try
