### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by gsergeantGTHB** [unixoide/5th-echelon#24]
I get connection failed whenever I try to either Login or Register a new account, how do I fix this?

Tried both old and new Ubisoft ID but nothing

EDIT: nevermind had to use dedicated_server first

**Comment by souhaibHadded03** [comment]
> I get connection failed whenever I try to either Login or Register a new account, how do I fix this?
> 
> Tried both old and new Ubisoft ID but nothing

did you run the dedicated server before selecting login inside the launcher? it gave me the same error when i forgot to run the dedicated server and only ran the launcher and clicked login, then when i ran the server before the launcher the login was successful

**Comment by souhaibHadded03** [comment]
> I get connection failed whenever I try to either Login or Register a new account, how do I fix this?
> 
> Tried both old and new Ubisoft ID but nothing
> 
> EDIT: nevermind had to use dedicated_server first

did your game run fine? i did everything correct but i can't run the game, it detects the change that happened to the dll file and gives me this error
![ERROR 6_4_2024 11_51_32 AM](https://github.com/unixoide/5th-echelon/assets/149155471/a1ecd04e-31b3-4302-9eb5-008e884071d9)

**Comment by gsergeantGTHB** [comment]
> > I get connection failed whenever I try to either Login or Register a new account, how do I fix this?
> > Tried both old and new Ubisoft ID but nothing
> > EDIT: nevermind had to use dedicated_server first
> 
> did your game run fine? i did everything correct but i can't run the game, it detects the change that happened to the dll file and gives me this error ![ERROR 6_4_2024 11_51_32 AM](https://private-user-images.githubusercontent.com/149155471/336423822-a1ecd04e-31b3-4302-9eb5-008e884071d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTk3ODksIm5iZiI6MTcxNzQ5OTQ4OSwicGF0aCI6Ii8xNDkxNTU0NzEvMzM2NDIzODIyLWExZWNkMDRlLTMxYjMtNDMwMi05ZWI1LTAwOGU4ODQwNzFkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxMTExMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjdkYzI2YzIxYmY5N2U3NjBiOWFjNDlhZTZiM2ZiNDExYWU4NDU1Y2JjN2JmNDNhYzVkOTFmODhiNjM1YmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UU5vlveuiFP30OU5DDypcc3n93YV6jrCORUobwrx3Z8)

Yeah, ingame go to video settings and change renderer to DX9

**Comment by souhaibHadded03** [comment]
> > > I get connection failed whenever I try to either Login or Register a new account, how do I fix this?
> > > Tried both old and new Ubisoft ID but nothing
> > > EDIT: nevermind had to use dedicated_server first
> > 
> > 
> > did your game run fine? i did everything correct but i can't run the game, it detects the change that happened to the dll file and gives me this error ![ERROR 6_4_2024 11_51_32 AM](https://private-user-images.githubusercontent.com/149155471/336423822-a1ecd04e-31b3-4302-9eb5-008e884071d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTk3ODksIm5iZiI6MTcxNzQ5OTQ4OSwicGF0aCI6Ii8xNDkxNTU0NzEvMzM2NDIzODIyLWExZWNkMDRlLTMxYjMtNDMwMi05ZWI1LTAwOGU4ODQwNzFkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxMTExMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjdkYzI2YzIxYmY5N2U3NjBiOWFjNDlhZTZiM2ZiNDExYWU4NDU1Y2JjN2JmNDNhYzVkOTFmODhiNjM1YmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UU5vlveuiFP30OU5DDypcc3n93YV6jrCORUobwrx3Z8)
> 
> Yeah, ingame go to video settings and change renderer to DX9

Thanks this helped, were you able to connect to online mode? I got the cannot download latest multiplayer data error, everything seems correct I'm pretty sure this should work but i don't know what i did wrong

**Comment by gsergeantGTHB** [comment]
> > > > I get connection failed whenever I try to either Login or Register a new account, how do I fix this?
> > > > Tried both old and new Ubisoft ID but nothing
> > > > EDIT: nevermind had to use dedicated_server first
> > > 
> > > 
> > > did your game run fine? i did everything correct but i can't run the game, it detects the change that happened to the dll file and gives me this error ![ERROR 6_4_2024 11_51_32 AM](https://private-user-images.githubusercontent.com/149155471/336423822-a1ecd04e-31b3-4302-9eb5-008e884071d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTk3ODksIm5iZiI6MTcxNzQ5OTQ4OSwicGF0aCI6Ii8xNDkxNTU0NzEvMzM2NDIzODIyLWExZWNkMDRlLTMxYjMtNDMwMi05ZWI1LTAwOGU4ODQwNzFkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxMTExMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjdkYzI2YzIxYmY5N2U3NjBiOWFjNDlhZTZiM2ZiNDExYWU4NDU1Y2JjN2JmNDNhYzVkOTFmODhiNjM1YmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UU5vlveuiFP30OU5DDypcc3n93YV6jrCORUobwrx3Z8)
> > 
> > 
> > Yeah, ingame go to video settings and change renderer to DX9
> 
> Thanks this helped, were you able to connect to online mode? I got the cannot download latest multiplayer data error, everything seems correct I'm pretty sure this should work but i don't know what i did wrong

Nope, I'm still trying to get it to work
Has to be something missing from the instructions, idk if 127.0.0.1 even works, not sure what i should put there in config server field and api server field

**Comment by souhaibHadded03** [comment]
> > > > > I get connection failed whenever I try to either Login or Register a new account, how do I fix this?
> > > > > Tried both old and new Ubisoft ID but nothing
> > > > > EDIT: nevermind had to use dedicated_server first
> > > > 
> > > > 
> > > > did your game run fine? i did everything correct but i can't run the game, it detects the change that happened to the dll file and gives me this error ![ERROR 6_4_2024 11_51_32 AM](https://private-user-images.githubusercontent.com/149155471/336423822-a1ecd04e-31b3-4302-9eb5-008e884071d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTk3ODksIm5iZiI6MTcxNzQ5OTQ4OSwicGF0aCI6Ii8xNDkxNTU0NzEvMzM2NDIzODIyLWExZWNkMDRlLTMxYjMtNDMwMi05ZWI1LTAwOGU4ODQwNzFkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxMTExMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjdkYzI2YzIxYmY5N2U3NjBiOWFjNDlhZTZiM2ZiNDExYWU4NDU1Y2JjN2JmNDNhYzVkOTFmODhiNjM1YmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UU5vlveuiFP30OU5DDypcc3n93YV6jrCORUobwrx3Z8)
> > > 
> > > 
> > > Yeah, ingame go to video settings and change renderer to DX9
> > 
> > 
> > Thanks this helped, were you able to connect to online mode? I got the cannot download latest multiplayer data error, everything seems correct I'm pretty sure this should work but i don't know what i did wrong
> 
> Nope, I'm still trying to get it to work Has to be something missing from the instructions, idk if 127.0.0.1 even works, not sure what i should put in config server field and api server field on launcher

From what i understood you have to replace 127.0.0.1 with your ip adress, just Google how to find my ip adress it's easy, the next problem is the cannot download latest multiplayer data error, hopefully we can figure it out
