### ISSUE TITLE
Compiling error OS error 5 with protoc

### ISSUE THREAD

**Issue by 0P3N50URC3-F0R3V3R** [unixoide/5th-echelon#26]
I have this problem upon compiling, the protoc is in place it has all read/write permissions, but i have ths error always... i am running everything as and Administrator. Win10. Nightly build for rust.  The error persists, i checked around in stackoverflow and all kind of sites but nothing solved. 
![image](https://github.com/unixoide/5th-echelon/assets/94479523/29f2f388-d065-4c21-b988-576bfa729e74)

Can someone give me some advice? I already been in defender and such, that is not solving this isue... I want to compile it myself... It is OS error 5 access denied. I even tried to put the proto in different folders.

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Its in both PATH and PROTOC on system and user setting in env. 
its on D:\protobuf\bin

**Comment by unixoide** [comment]
`PROTOC` should point to the binary, not the directory. For example `D:\protobuf\bin\protoc.exe`. Or try to only set the `PATH`?

**Comment by 0P3N50URC3-F0R3V3R** [comment]
Ding!Ding!Ding! We have a winner :D I needed to point directly to the exe the PROTOC

![image](https://github.com/unixoide/5th-echelon/assets/94479523/a12e64ce-fe1d-40a0-a62e-27d6611002e2)

**Comment by 0P3N50URC3-F0R3V3R** [comment]
TXH for your help!
