### ISSUE TITLE
User credentials required

### ISSUE THREAD

**Issue by TheConen** [unixoide/5th-echelon#3]
Hi there!

I was very excited seeing this and tried using it.
It seems that you need to configure some user credentials in uplay.toml - I'm getting "Login failed for sam_the_fisher" errors with the default configuration. In your video I saw you using the user "AAAABBBB".

Can you provide some information/documentation on how to create a new user or which user to use?

**Comment by JordanLeich** [comment]
I had the same issue, here's the fix. https://github.com/unixoide/5th-echelon/issues/1#issuecomment-1831872321

**Comment by TheConen** [comment]
Thanks a lot, that worked.

I guess there is no way to create your own users, yet?
Would it be possible for someone else to join this server with the same username/password that I am using?

Another thing: when using this, it seems to use a new game profile (new saves, new settings etc.). Do you know if it is possible to use your existing profile with your unlocks, loadouts etc.?

**Comment by JordanLeich** [comment]
> Thanks a lot, that worked.
> 
> 
> 
> I guess there is no way to create your own users, yet?
> 
> Would it be possible for someone else to join my server with the same username/password that I am using?
> 
> 
> 
> Another thing: when using this, it seems to use a new game profile (new saves, new settings etc.). Do you know if it is possible to use your existing profile with your unlocks, loadouts etc.?

I'm not actually sure, maybe the database file has to be edited? but I don't know.
As of right now, I don't think matchmaking with other players works at all so I don't know the answer to your second question.
I had the same thing happen to me where the game starts you from the very beginning, I'm also not sure if there's a workaround for this or not.

**Comment by unixoide** [comment]
Sorry for the login issue. I pushed new changes and binaries which also include `sam_the_fisher` in the database.

Adding accounts is not exposed yet. You can add them to the database manually with a SQLITE database editor. The password has to be stored as `argon2id` in encoded form. You can use https://argon2.online/ to encode it.

> Would it be possible for someone else to join my server with the same username/password that I am using?
No, this is not fully implemented yet (see the repository readme).

> when using this, it seems to use a new game profile (new saves, new settings etc.). Do you know if it is possible to use your existing profile with your unlocks, loadouts etc.?
The new uplay dll stores the save games at a different location with a slightly different format. So you can't use your old save games with it (yet). But it leaves the original saves untouched, so you won't loose anything and copying the `uplay_r1_loader.orig.dll` back to `uplay_r1_loader.dll` will give you access to your old saves again.
