### ISSUE TITLE
Client: Blacklist service not available.

### ISSUE THREAD

**Issue by Icexdd** [unixoide/5th-echelon#30]
Hello!
I'm trying to get this to work. The host works and can make a lobby. The client can log in via the launcher and start the game. However, whenever the client tries to connect an error pops up saying "The splinter cell blacklist service is unavailable."

**Comment by cloudslsw** [comment]
im same with you

**Comment by pelmenipadi** [comment]
experiencing the same issue as OT, fix by cloudslsw doesnt work. Sometimes even the host cannot join online

**Comment by gsergeantGTHB** [comment]
same error, all required ports forwarded but clients keep getting service unavailable no matter, only hosts are able to get in.

**Comment by pelmenipadi** [comment]
I could fix it by changing 127.0.0.1 in service.toml to my Hamachi IP at all places.

**Comment by Koteyka-dev** [comment]
> I could fix it by changing 127.0.0.1 in service.toml to my Hamachi IP at all places.


Thank you for solution! We tried it with @gsergeantGTHB and server is running well now.

**Comment by Icexdd** [comment]
> I could fix it by changing 127.0.0.1 in service.toml to my Hamachi IP at all places.

The host or the client?

**Comment by Icexdd** [comment]
> I could fix it by changing 127.0.0.1 in service.toml to my Hamachi IP at all places.

This worked!
