### ISSUE TITLE
Both connected to online mod, but can't find each other using the find teammate button 

### ISSUE THREAD

**Issue by souhaibHadded03** [unixoide/5th-echelon#48]
We used to play just fine in the previous version, but now for some reason after this dx11 update, we are only able to connect to online mode, but we can't join each other at all after clicking find teammate each one of us finds himself alone in lobby, that wasn't the case in the previous version, any idea why is that?

**Comment by Whoisgold** [comment]
You both have to delete the fix and to install the previous version of it. Go to SteamLibrary\steamapps\common\Tom Clancy's Splinter Cell Blacklist\src\SYSTEM, delete uplay_r1_loader.dll and rename uplay_r1_loader.orig.dll without .orig. Then download the fix again from here https://github.com/unixoide/5th-echelon/releases/tag/2024-06-03 and it will work.

**Comment by souhaibHadded03** [comment]
> You both have to delete the fix and to install the previous version of it. Go to SteamLibrary\steamapps\common\Tom Clancy's Splinter Cell Blacklist\src\SYSTEM, delete uplay_r1_loader.dll and rename uplay_r1_loader.orig.dll without .orig. Then download the fix again from here https://github.com/unixoide/5th-echelon/releases/tag/2024-06-03 and it will work.

have you tried this method and it worked for you? cause even when we went back to the old version we're still encountering the same issue, find teammate,and then each one of us is alone :( we used to play a lot before, don't know what's wrong now

**Comment by Whoisgold** [comment]
> > You both have to delete the fix and to install the previous version of it. Go to SteamLibrary\steamapps\common\Tom Clancy's Splinter Cell Blacklist\src\SYSTEM, delete uplay_r1_loader.dll and rename uplay_r1_loader.orig.dll without .orig. Then download the fix again from here https://github.com/unixoide/5th-echelon/releases/tag/2024-06-03 and it will work.
> 
> have you tried this method and it worked for you? cause even when we went back to the old version we're still encountering the same issue, find teammate,and then each one of us is alone :( we used to play a lot before, don't know what's wrong now

It worked for me and my friend. Add me on discord, Itll be easier for me to help you guys (goldenapple._)

**Comment by souhaibHadded03** [comment]
> > > You both have to delete the fix and to install the previous version of it. Go to SteamLibrary\steamapps\common\Tom Clancy's Splinter Cell Blacklist\src\SYSTEM, delete uplay_r1_loader.dll and rename uplay_r1_loader.orig.dll without .orig. Then download the fix again from here https://github.com/unixoide/5th-echelon/releases/tag/2024-06-03 and it will work.
> > 
> > 
> > have you tried this method and it worked for you? cause even when we went back to the old version we're still encountering the same issue, find teammate,and then each one of us is alone :( we used to play a lot before, don't know what's wrong now
> 
> It worked for me and my friend. Add me on discord, Itll be easier for me to help you guys (goldenapple._)

We reinstalled the game and somehow that fixed the issue the old dx9 patch works fine thank you, any hope we can use the latest version?

**Comment by Whoisgold** [comment]
> > > > You both have to delete the fix and to install the previous version of it. Go to SteamLibrary\steamapps\common\Tom Clancy's Splinter Cell Blacklist\src\SYSTEM, delete uplay_r1_loader.dll and rename uplay_r1_loader.orig.dll without .orig. Then download the fix again from here https://github.com/unixoide/5th-echelon/releases/tag/2024-06-03 and it will work.
> > > 
> > > 
> > > have you tried this method and it worked for you? cause even when we went back to the old version we're still encountering the same issue, find teammate,and then each one of us is alone :( we used to play a lot before, don't know what's wrong now
> > 
> > 
> > It worked for me and my friend. Add me on discord, Itll be easier for me to help you guys (goldenapple._)
> 
> We reinstalled the game and somehow that fixed the issue the old dx9 patch works fine thank you, any hope we can use the latest version?

Yep you can, but you have to uninstall the old version before running the latest one https://github.com/unixoide/5th-echelon?tab=readme-ov-file#uninstalling-the-mod
