### ISSUE TITLE
Issue while booting game from Uplay.

### ISSUE THREAD

**Issue by Rabbit234** [unixoide/5th-echelon#5]
Hey, 

i have tried to get this running and replaced the DLL like shown in the tutorial. If I start the game via the UPLAY Launcher it tells me, that the exe file was modified and is not supported in DX11 Mode.

![bc_issue01](https://github.com/unixoide/5th-echelon/assets/7255603/44b1309e-ce3f-44da-847f-f00abb136619)

If I try to start the Blacklist_game.exe directly in the SYSTEM Folder it comes up with the following error. After clicking OK there is another error message coming up.
![bc_issue02](https://github.com/unixoide/5th-echelon/assets/7255603/85bf52d5-98ce-4238-b371-50cca2b6eb39)
![bc_issue03](https://github.com/unixoide/5th-echelon/assets/7255603/e172811b-8400-4872-8c87-efaa9df7232e)

The SHA256 hash of my blacklist file is.

SHA256          7FCD3A18D4DCC692719984B07268BD42764108E7DF37049F1490F20929F9925D       Blacklist_game.exe
SHA256          C52B3D0927591E477424F389FF0B1314A300938E19CE61A7B0A7BC09F81C2C89         Blacklist_DX11_game.exe

Is there already a fix for this issue? 

Thanks in advance!

**Comment by JordanLeich** [comment]
@Rabbit234 this zip should be the fix. https://github.com/unixoide/5th-echelon/releases/tag/2023-11-29

**Comment by TheConen** [comment]
I had that exact error when I didn't rename the original dll to exactly how it is described in the readme. The modified DLL depends on the original dll and expects it to be named exactly `uplay_r1_loader.orig.dll`.

**Comment by Rabbit234** [comment]
Thanks!

Its working now! 
The first issue was me not exactly following the documentation and called the file copy.ddl expecting it to be just for backup reason.

Renaming the DDL file did not start the game and the DX11 Error (not supported) still comes up. I fixed it by using the original game data and go into video settings inside the Game changing DX11 into DX9 manually and doing the steps you posted again!

It's all working now. Thanks a lot for your hard work. I really appreciate it! :)
