### ISSUE TITLE
how do i set up

### ISSUE THREAD

**Issue by Azurefel** [unixoide/5th-echelon#6]
game won't launch, as there is no uplay_r1_loader.dll within the folder for me to use, make usage more clear

**Comment by TheConen** [comment]
The `uplay_r1_loader.dll` is located in `%YOUR_INSTALLATION_FOLDER%/src/SYSTEM`, not at the root level of your installation folder.

**Comment by Azurefel** [comment]
> The project currently requires that the game is installed via Ubisoft Connect. Where have you bought the game from? Can you share exe files?

i have it on ubisoft connect, idk how to set up this file/folder

**Comment by unixoide** [comment]
As said by @TheConen you need to go to the game install directory and then src/SYSTEM. Then rename the uplay_r1_loader.dll and copy the new one there.
