### ISSUE TITLE
"Friend system"

### ISSUE THREAD

**Issue by Sylwester1766** [unixoide/5th-echelon#9]
Hi. My friend and I are trying to join each other's lobbies but completely have no idea what to do in case we both have the name "aaaabbbb" and the password "ccccdddd". When I send an invitation to the lobby to user "aaaabbbb" then I invite myself :P 

Author of the modification, please describe in more detail how the new system works so that the community can help :)

**Comment by K4CZP3R** [comment]
You can change your username in the config file and then add the new user to the database by either modifying the sql file or the migration.

**Comment by unixoide** [comment]
Invite system uses the backend server to send an invite to other players known on the server. It does not check for multiple logins. Another test account to play around with is "sam_the_fisher" with the password "password1234"
